### ISSUE TITLE
Accidentally made two branches for one thing

### ISSUE THREAD

**Issue by smishra2** [routemaster/routemaster-web#12]
I accidentally made features/webserver and webserver. I pushed to webserver on accident. How do i delete the current features/webserver and rename "webserver" to "features/webserver"?

**Comment by smishra2** [comment]
Also note that when running maven on the server, mvn package by itself did not seem to work. Rather, I used "mvn clean compile exec:java"

**Comment by kalgynirae** [comment]
Get the branches straightened out on your machine first. You can use `git branch -d <branchname>` to delete and `git branch -m <oldname> <newname>` to rename. Then push. Don't worry about the "webserver" branch you pushed; Ben or I will clean that up along with all the other old feature branches.

> mvn package by itself did not seem to work.

Post the output somewhere so we can see what went wrong?

**Comment by smishra2** [comment]
well basically when i ran "mvn package", it worked. but when i ran the snapshot .jar, it returned a ClassDefNotFound Exception for one of the Jetty classes I used in the server, namely AbstractHandler. However, when I did "mvn clean compile exec:java", it was able to run the server locally on the machine.

**Comment by bgw** [comment]
@smishra2 Nice catch. I think the issue is that maven doesn't bundle dependencies in the jar. `mvn exec:java` manipulates the classpath to fix that though. I guess we have two options:
- Always use `mvn exec:java` to run the program, like you're doing now
- Build a redistributable and portable jar with [maven-assembly-plugin](http://stackoverflow.com/a/574650/130598)

I think I'll try the second and send pull requests to the frontend and backend soon.
